### ISSUE TITLE
Configure wercker.yml for automated CI

### ISSUE THREAD

**Issue by brunoborges** [oracle/terraform-examples#14]
Please add a wercker.yml file, similarly to the one on [terraform-provider-baremetal](https://github.com/oracle/terraform-provider-baremetal/blob/master/wercker.yml).

This will allow us to do continuous build upon new Pull Requests.

**Comment by scross01** [comment]
@brunoborges We are no longer building the provider from this repo - all Terraform for OPC development has moved to the Hashicorp repo at https://github.com/terraform-providers/terraform-provider-opc.
