### ISSUE TITLE
LB nodes in the diagram are in public subnets, but description says otherwise

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle/terraform-examples#27]
https://github.com/oracle/terraform-examples/blob/master/examples/oci/regional_private_lb/README.md

The intro reads: "two private load balancers" ...

But the architecture diagram has the LB nodes in public subnets.

**Comment by alexng-canuck** [comment]
@kumar-dhanagopal , this issue is now fixed in the documentation.
